#!/bin/sh

# This script displays battery icon according to the charge level and charging state

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `acpi`

bat=$(acpi -b)
state=$(echo ${bat} | awk '{print $3}')

if [[ "$state" = "Not" ]]; then
    level=$(echo ${bat} | awk '{print $5}')
    level=${level::-1}

else
    level=$(echo ${bat} | awk '{print $4}')
    if [[ "$state" == *"Unknown"* ]]; then
        level=${level::-1}
    else
        if [[ "$level" == "100%" ]]; then
          level=${level::-1}
        else
          level=${level::-2}
        fi
    fi
fi

if [[ "$bat" == *"until"* ]]; then

    if [[ "$level" -ge "95" ]]; then
        #echo 󰂄
        echo "<span foreground='#4caf50'>󰂄</span>" "${level}%"
    elif [[ "$level" -ge "75" ]]; then
       # echo 󰢞 
       echo "<span foreground='#4caf50'>󰢞</span>" "${level}%"
    elif [[ "$level" -ge "35" ]]; then
       # echo 󰢝
       echo "<span foreground='#4caf50'>󰢝</span>" "${level}%"
    elif [[ "$level" -ge "15" ]]; then
       # echo 󰂆
       echo "<span foreground='#4caf50'>󰂆</span>" "${level}%"
    else
       # echo 󰢟
       echo "<span foreground='#4caf50'>󰢟</span>" "${level}%"
    fi
else
    if [[ "$level" -ge "95" ]]; then
        echo 󰁹 "${level}%"
    elif [[ "$level" -ge "75" ]]; then
        echo 󰂀 "${level}%"
       # echo "<span foreground='#ff4d4d'>󰁻</span>"
    elif [[ "$level" -ge "35" ]]; then
        echo 󰁾 "${level}%"
    elif [[ "$level" -ge "25" ]]; then
    	echo "<span foreground='#ff4d4d'>󰁻</span>"
       # echo ~/tint2-executors/images/bat-quarter.svg 
    else
        echo 󰂎 "${level}%"
    fi
fi
#printing to stderr shows as tooltip in tint2 
echo "${level}% • ${state}" >&2
