#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox"
STYLE="red"
RASI="$DIR/themes/$STYLE/rofi/launcher.rasi"

# Run
# rofi -show calc -modi calc -no-show-match -no-sort -theme ${RASI}

rofi -show calc -modi calc -no-show-match -no-sort -theme ${RASI}