#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Brightness Executor For Tint2

# Graphics card
CARD=`ls /sys/class/backlight | head -n 1`

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" "$(light -G)")
	echo "${LIGHT}%"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "25") ]]; then
		icon=''
	elif [[ ("$current" -ge "25") && ("$current" -le "50") ]]; then
		icon=''
	elif [[ ("$current" -ge "50") && ("$current" -le "75") ]]; then
		icon=''
	elif [[ ("$current" -ge "75") && ("$current" -le "100") ]]; then
		icon=''
	fi
}

# Get status
get_status() {
	get_icon
	if [[ -n "$CARD" ]]; then
		echo "$icon $(get_backlight)"
	else
		echo "$icon NA"
	fi
}

# Increase brightness
inc_backlight() {
	light -A 5
}

# Decrease brightness
dec_backlight() {
	light -U 5
}

# Execute accordingly
if [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	echo "`get_status`"
fi
